### ISSUE TITLE
Cards not clicking through to deep_link url, tooltips not shown

### ISSUE THREAD

**Issue by macdis** [custom-cards/upcoming-media-card#112]
## Describe the bug:

The main thing is that `url:`  does not seem to function with the deep_link coming from the Plex Recently Added integration. Also:  `enable_tooltips: true` does not function with Plex Recently Added integration.
I'm not sure that these issues are related, but maybe so, so I'm including them both.
Could this be about a DOM change?

## Config YAML:

```yaml
title: Recently Added Movies
type: custom:upcoming-media-card
entity: sensor.plex_recently_added_movie
max: 5
image_style: fanart
hide_unflagged: true
enable_tooltips: true
enable_transparency: true
url: "{{ state_attr('sensor.plex_recently_added_movie','data')[1].deep_link }}"

```
## Components:

`sensor.plex_recently_added` from https://github.com/custom-components/sensor.plex_recently_added

## HA Error:

There is no error in the HA log.

## Troubleshooting Guide:

I followed the steps. The card displays all data correctly, but is not clickable (deep_link) and does not show tool_tips (summary).

## Home Assistant Version:

Core 2025.4.3
Supervisor 2025.04.0
Operating System 15.2
Frontend 20250411.0

## Additional Context:

`"{{ state_attr('sensor.plex_recently_added_movie','data')[1].deep_link }}"` does correctly return url data in the dev tools template editor, as follows (for example): `http://192.168.1.110:32400/web/index.html#!/server/123456/details?key=%2Flibrary%2Fmetadata%2F5007`
Browsers used: Chrome, Firefox (history wiped).
Also tried the HA iOS app.
