### ISSUE TITLE
card doesn't show up, get JSON error

### ISSUE THREAD

**Issue by jkirkcaldy** [custom-cards/upcoming-media-card#14]
Followed the instructions on how to install but when I open the page the card should show on there is nothing there. 

Checking the logs shows:

    2018-11-13 14:36:37 ERROR (MainThread) [frontend.js.latest.201810264] http://$ipaddress:8123/local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0:16:28 SyntaxError: JSON Parse error: Unexpected identifier "undefined",

**Comment by maykar** [comment]
Going to need a bit more info.

Which component are you using? Does the sensor show any data in developer tools > states in HA? What's the code in your ui-lovelace.yaml look like? etc.

**Comment by jkirkcaldy** [comment]
I have tried with both Sonarr and Radarr, both of which show the correct data in the developer tools. 
In my config I have set up both sonarr and radarr with the following:

```
  - platform: radarr
    api_key: $API
    host: $ipaddress
    urlbase: /radarr
    monitored_conditions:
      - diskspace
      - upcoming
    unit: TB
    days: 7
    
  - platform: sonarr
    api_key: $API
    host: $ipaddress
    urlbase: /sonarr
    monitored_conditions:
      - diskspace
      - upcoming
    unit: TB
    days: 7  
```

ui-lovelace.yaml
```
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.2.9
    type: js 
.......

.......
  - icon: mdi:server
    title: Server
    cards:
    - id: media
      name: Sonarr
      type: custom:upcoming-media-card
      entity: sensor.sonarr_upcoming
    - id: radarr
      name: Radarr
      type: custom:upcoming-media-card
      entity: sensor.radarr_upcoming
```
