### ISSUE TITLE
AM/PM not hidden with clock_am_pm set to false

### ISSUE THREAD

**Issue by iantrich** [custom-cards/upcoming-media-card#19]
```yaml
clock: options
clock_am_pm: false
type: 'custom:compact-custom-header'
```
![image](https://user-images.githubusercontent.com/1287159/50719484-1cf26d80-1062-11e9-8ce7-14650b0704c8.png)
When set to `true` the style does change, however
![image](https://user-images.githubusercontent.com/1287159/50719487-31366a80-1062-11e9-9a20-2a4db491e485.png)
