### ISSUE TITLE
Not gatting data from radarr

### ISSUE THREAD

**Issue by gbdavidx** [custom-cards/upcoming-media-card#20]
I have radarr on http://192.168.1.189:8310/ (8310), modified in the sensors, sonarr works fine 

in the dev-state it says online, but the data is [] empty, i have the movie bumble bee in my queue
**sensors.yaml file**
```
- platform: radarr_upcoming_media
  api_key: 2799e84ddbe245639b2ef6903580b60e
  host: 192.168.1.XXX
  port: 8310
  days: 365
  ssl: false
```
**lovelace.yaml file**
```
resources:
- url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js
  type: js
```
sonarr works fine, i doubt its my lovelace config, since the dev state shows online, however there's no media imported
```
views:
  - id: 0
    name: Home
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: entities
            title: Whose Home
            show_header_toggle: false
            entities:
              - input_boolean.david_occupancy
          - type: horizontal-stack
            cards:
             - type: light
               entity: light.23460a
             - type: light
               entity: light.2349a5
             - type: light
               entity: light.dining_room
          - type: sensor
            entity: sensor.thermostat_temperature
            name: Home Temperature
          - type: sensor
            entity: sensor.thermostat_humidity
            name: Home Humidity
          - break
          - type: custom:upcoming-media-card
            entity: sensor.radarr_upcoming_media
          - break
          - type: custom:upcoming-media-card
            entity: sensor.sonarr_upcoming_media

```
i have cleared the cache and re-downloaded the radarr_upcoming_media.py in the same folder as sonarr_upcoming_media, i am on Home Assistant 0.84.6
