### ISSUE TITLE
Spacing issue

### ISSUE THREAD

**Issue by benjgos** [custom-cards/upcoming-media-card#36]
## Describe the bug:

upcoming-Sonarr - The space between each episode seems incorrect compared to the example screenshots.
Is there a way to resize that space?

## Config YAML:

```yml
              - type: custom:upcoming-media-card
                entity: sensor.sonarr_upcoming_media
                clock: 24
                all_shadows: false
                line3_text: '$number - $studio'
                line4_text: '$empty'
```
This seems the same without anything but the default (type and entity only)
## Components:

Component: sonarr_upcoming_media only
## Home Assistant Version:

HASS 0.98.1
## Screenshots:

iOS HASS Mobile app view: 
![mobile_screenshot](https://user-images.githubusercontent.com/232766/64299878-68864f80-cf40-11e9-806b-7a7fff0cbf94.jpg)

Browser (Safari Mac) view:
<img width="449" alt="browser_screenshot" src="https://user-images.githubusercontent.com/232766/64299890-7cca4c80-cf40-11e9-9dbe-8ecb3b56f1ac.png">
