### ISSUE TITLE
No card type found / No card type configured.

### ISSUE THREAD

**Issue by BrettWa** [custom-cards/upcoming-media-card#39]
I've followed the instructions and double checked - when I try adding the card to my UI, I get the "No card type found / No card type configured." message.
```
- type: custom:upcoming-media-card
  entity: sensor.sonarr_upcoming_media
  title: Upcoming TV
```

I've copied the script to homeassistant/www/custom-lovelace/upcoming-media-card

In my lovelace.ui I have the following as per instructions:
```
- url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.1.1
    type: js
```
I can see the above script by browsing to https://MYIP/local/custom-lovelace/upcoming-media-card/upcoming-media-card.js

I have copied the three files to: homeassistant/custom_components/sonarr_upcoming_media

I can see the  sensor.sonarr_upcoming_media state, and it's populated.

I've tried clearing my browser cache, and using a different browser?

Nothing in the logs either.

What am I missing?

**Comment by BrettWa** [comment]
After a restart, I have this in the log:
https://myip/local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.1.1:1:1 Uncaught SyntaxError: Identifier 'UpcomingMediaCard' has already been declared

I only have the one decleration under resources though?

**Comment by maykar** [comment]
`type: js` should not be indented:
```
- url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.1.1
  type: js
```

If you're still having issues please share the config for the card.

**Comment by BrettWa** [comment]
It is indented correctly, the copy and paste here is messing it up, here's what I have under resources:
```
resources:
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.1.1
    type: js
  - type: module
    url: /local/custom-lovelace/weather-card/weather-card.js
  - type: module
    url: /local/mini-graph-card-bundle.js?v=0.7.0
  - type: module
    url: >-
      /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.0.1
```

and for the card:
```
- type: 'custom:upcoming-media-card'
  entity: sensor.sonarr_upcoming_media
```
I'm not sure why the log file error states it's already been declared, I've searched the .yaml file, and only find the one reference in the top:
Identifier 'UpcomingMediaCard' has already been declared
