### ISSUE TITLE
Platform not found: sensor.sonarr_upcoming_media

### ISSUE THREAD

**Issue by IIIdefconIII** [custom-cards/upcoming-media-card#4]
ui-lovelace.yaml
```
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js
    type: js
  - url: /local/custom-lovelace/radarr_upcoming_media.py
    type: py
  - url: /local/custom-lovelace/sonarr_upcoming_media.py
    type: py
```

```
      - type: custom:upcoming-media-card
        service: sonarr  

      - type: glance
        title: ''
        column_width: calc(100% / 4)
        entities:
          - entity: sensor.radarr_upcoming_media
          - entity: sensor.sonarr_upcoming_media
```

sonarr.yaml
```
###### SENSORS -------------------------------------------------
############################################
##                 SONARR                 ##
############################################
homeassistant:
  customize:

###### SENSORS -------------------------------------------------
sensor:
  - platform: sonarr_upcoming_media
    api_key: !secret api_key_sonarr
    host: 10.3.1.2
    port: 8989
    days: 2
    ssl: false

###### PANELS -------------------------------------------------
panel_iframe:
  sonarr:
    title: 'Sonarr Shows Download'
    icon: mdi:filmstrip
    url: 'http://10.3.1.2:8989'
```
https://imgur.com/a/C5fxqSz
https://imgur.com/a/rRVIdSp

error:
Platform not found: sensor.radarr_upcoming_media
Platform not found: sensor.sonarr_upcoming_media

Im not sure what im missing here
