### ISSUE TITLE
Custom element doesn't exist: upcoming-media-card.

### ISSUE THREAD

**Issue by GMFalka** [custom-cards/upcoming-media-card#42]
## Describe the bug:
Using HACS to install this plugin, but card doesnt load up(?)

## Config YAML:
```
resources:
    url: /local/light-entity-row.js?v=0
  - type: js
title: Home
views:
  - cards:
```

## HA Error:
`Custom element doesn't exist: upcoming-media-card.`

## Home Assistant Version:
Home Assistant 0.103.4

## Additional Context:
Just installed HACS, restart everything. Tried other lovelace plugin too, but they are not loading either.
Help would be greatly appreciated!
