### ISSUE TITLE
Dashboard completely disappear after using custom

### ISSUE THREAD

**Issue by Bios-dude** [custom-cards/upcoming-media-card#67]
## Config YAML:  
```
views:
  - badges: []
    cards:
      - type: 'custom:upcoming-media-card'
        entity: sensor.sonarr_upcoming
```

## Screenshots: 
![Screenshot_32](https://user-images.githubusercontent.com/63623759/113479757-0181a180-94bb-11eb-9f71-bdc1bd4f69af.png)
