### ISSUE TITLE
Error from HA Log - No Version Key

### ISSUE THREAD

**Issue by AbhiOommen** [custom-cards/upcoming-media-card#68]
Please see the log entry below from HA, just wanted to post and let you know, if someone hasn't already, I couldn't find an issue related to this.

```
Logger: homeassistant.loader
Source: loader.py:794
First occurred: 3:00:07 PM (3 occurrences)
Last logged: 3:00:07 PM

No 'version' key in the manifest file for custom integration 'plex_recently_added'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'plex_recently_added'
No 'version' key in the manifest file for custom integration 'radarr_upcoming_media'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'radarr_upcoming_media'
No 'version' key in the manifest file for custom integration 'sonarr_upcoming_media'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'sonarr_upcoming_media'
```

Upcoming media card Installed through HACS. My sensor configuration below:
```
- platform: plex_recently_added
  name: New Movies # will create sensor.new_movies
  token: !secret plex_token
  host: !secret host
  port: 32400
  section_types:
    - movie

- platform: plex_recently_added
  name: New TV # will create sensor.new_tv
  token: !secret plex_token
  host: !secret host
  port: 32400
  section_types:
    - show

- platform: radarr_upcoming_media
  api_key: !secret radarr_english_api
  host: !secret host
  port: 7878
  days: 14
  ssl: false
  theaters: true
  max: 10

- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api
  host: !secret host
  port: 8989
  days: 7
  ssl: false
  max: 10
```
