### ISSUE TITLE
Cannot find the Upcoming-media-card

### ISSUE THREAD

**Issue by asemev** [custom-cards/upcoming-media-card#79]
## Describe the bug:

Hi guys, i'd appreciate a lot if someone could lend me a hand. I have installed and followed the instructions and checked all the open and closed issues and tried some of the recommendations and also checked the troubleshooting guide but to no avail. I cleared the cache, i disabled adguard. I just cannot see the upcoming-media-card in the list of custom cards when trying to add it to lovelace. Thank you in advance.

![image](https://user-images.githubusercontent.com/30929896/148662755-756e5e17-8d46-4928-9aa1-57956f9bb952.png)
![image](https://user-images.githubusercontent.com/30929896/148662811-27fce799-27b3-46ab-bd2b-58bb275fefc8.png)

Here are the steps how i installed:

- I installed the "Upcoming Media Card" via HACS. version 0.4.3
![image](https://user-images.githubusercontent.com/30929896/148662551-dce762c1-0e43-4fa8-8ccd-71f5845f6e11.png)

- I also installed the "Sensor.Plex recently added" component in HACS.
![image](https://user-images.githubusercontent.com/30929896/148662563-145bc071-7199-4122-b0b3-152ee5b36ec1.png)

- I double checked to make sure the resources entry is correctly listed (/hacsfiles/upcoming-media-card/upcoming-media-card.js?hacstag=146783593043)
![image](https://user-images.githubusercontent.com/30929896/148662541-38c07112-dd5f-4d95-87a3-259b536c9b4c.png)

- The interesting thing is that the javascript is working. I can see that it created a folder and downloaded the artwork from plex.
![image](https://user-images.githubusercontent.com/30929896/148662348-9215bc37-868e-4041-a7c0-6b5453363a18.png)

## Config YAML:

'''
```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes
    
http:
  use_x_forwarded_for: true
  trusted_proxies: 172.30.33.0/24

homeassistant:
  name: Home
  latitude: xxx
  longitude: xxx
  elevation: 143
  unit_system: metric
  time_zone: Europe/Berlin
  external_url: "https://xxx.duckdns.org"
  internal_url: "http://xxxx:8123"

group: !include groups.yaml
automation: !include automations.yaml

sensor:
  - platform: plex_recently_added
    name: Recently Added Movies # will create sensor.recently_added_movies
    token: xxx
    host: xxx
    port: 32400
    section_types:
      - movie
  - platform: plex_recently_added
    name: Recently Added TV  # will create sensor.recently_added_tv
    token: xxx
    host: xxx
    port: 32400
    section_types:
      - show

lovelace:
  resources:
    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module
```
'''

## HA Error:

I dont see any errors in the logs.

## Home Assistant Version:
2021.12.8
Home Assistant OS 7.1
