### ISSUE TITLE
Unable to Sort card with data from Plex_Recently_Added sensor

### ISSUE THREAD

**Issue by mayorgergich** [custom-cards/upcoming-media-card#91]
## Describe the bug:
I'm unable to sort anything other than the default value 'airdate'

## Config YAML:
```
     - type: custom:upcoming-media-card
        entity: sensor.plex_recently_added
        title: Recently Downloaded
        sort_by: release_date (have tried other options here. None work)
```

## Components:
1. Plex Recently Added Sensor
2. Upcoming Media Card

## HA Error:
No Errors appear in logs

## Troubleshooting Guide:

I have uninstalled and reinstalled the inteegration, confirmed all settings in plex receently added are correct and connection to server is confirmed.

## Home Assistant Version:

2024.5.3

## Screenshots:
None would provide extra context.

## Additional Context:
None

**Comment by mkanet** [comment]
Hi, if you want to use `sort_by:`  you will need to reference the correct attribute names.  Developer Tools /States (shown in the screenshot below) will show you the available attributes for each sensor.  For example, below is what I use for `sensor.recently_added_movies`.  Please note that some of the attributes are not compatible with the `sort_by` and `collapse` features

```
title: Movies
type: custom:upcoming-media-card
entity: sensor.recently_added_movies
image_style: fanart
hide_empty: true
box_shadows: true
enable_tooltips: true
enable_transparency: true
sort_by: airdate
collapse: flag=true
```
![image](https://github.com/custom-cards/upcoming-media-card/assets/811008/7f5d7bf6-aec5-4814-8def-2212b2de29f1)

**Comment by BernieV1977** [comment]
I have the same problem, Sorting doesn't work, also with other cards .

**Comment by mkanet** [comment]
> I have the same problem, Sorting doesn't work, also with other cards .

HI if you are doing the same thing as the OP, please see my response.

**Comment by BernieV1977** [comment]
> > I have the same problem, Sorting doesn't work, also with other cards .
> 
> HI @BernieV1977, if you are doing the same thing as the OP, please see my reply. In his example, he was not referencing a valid attribute.

I tried sorting on airdate, studio, ... with attributes that exist in the sensor.

**Comment by mayorgergich** [comment]
I've done the same as well, and gave a poor example. I've identified the attributes within the sensor I want to sort by and none of the available options work.

**Comment by mkanet** [comment]
> I've done the same as well, and gave a poor example. I've identified the attributes within the sensor I want to sort by and none of the available options work.

Thank you for trying the other attributes.  Can you plesse confirm you can use some of the other new features of UMC like transparency, collapse, etc.  We need to confirm you are using effectively using the new new version of UMC or the really old version. If none of the new features work, that is a strong indicator that your
 setup is still using the old version.

**Comment by mkanet** [comment]
Hi @BernieV1977 thank you for posting the card code.  I forgot to ask you this, can you please confirm that the other new features on UMC actually work?  For example, `collapse:` `enable_transparency:` and deep_links?  For example, when you click on a show or movie, does it open your Plex Server's Webpage for the respective show or movie you just clicked?

If the other features don't work either, it is likely your are still effectively using the old version of UMC.

Very Important:  In many cases, after you upgrade UMC, it requires deleting your web browser's cache after you upgrade and reboot Home Assistant.  I actually clear my browser's cache after each upgrade of UMC.

**Comment by mkanet** [comment]
@BernieV1977 and @mayorgergich.  Can you please confirm that the other new features work in UMC _I.E._, Clickable hyperlinks (takes you to the respective deep_link URL), Collapse filter, and Transparency?  If none of those features work, it would mean you aren't using the original Repo for Upcoming Media Card.  

If the sort feature is indeed the only feature that doesn't work at all, please let me know.

**Comment by BernieV1977** [comment]
> @BernieV1977 and @mayorgergich. Can you please confirm that the other new features work in UMC _I.E._, Clickable hyperlinks (takes you to the respective deep_link URL), Collapse filter, and Transparency? If none of those features work, it would mean you aren't using the original Repo for Upcoming Media Card.
> 
> If the sort feature is indeed the only feature that doesn't work at all, please let me know.

I have no Plex so can't test the deep links feature. I only use the cards for Trakt. I'm on version 0.4.4.

**Comment by mkanet** [comment]
@BernieV1977 thanks for letting me know.  I appreciate it.  I have a feeling the issue might be related to the Integration you're using with UMC, trakt.  I developed the sorting feature using `Radarr Upcoming Media`, `Sonarr Upcoming Media`, and `Plex Recently Added` integrations.  As soon as I get some time.  I'll install the trakt integration to see if I can reproduce what you are seeing.

In the meantime, can you please copy and paste the text from the Attributes section (under Developer Tools\STATES) for the trakt sensor you're using like the below example?  Make sure you copy the text starting from the very first line and include 2-3 items like the below example.  Please also try to keep the formatting/indentation intact (just like below).  Also, post the respective state value for this sensor.

```
data:
  - title_default: $title
    line1_default: $episode
    line2_default: $release
    line3_default: $rating - $runtime
    line4_default: $number - $studio
    icon: mdi:arrow-down-bold
  - airdate: "2024-04-09T00:00:00Z"
    release: Available Online $day
    flag: true
    title: Kung Fu Panda 4
    runtime: 94
    studio: DreamWorks Animation
    genres: Animation, Action, Family
    rating: ""
    summary: >-
      Po is gearing up to become the spiritual leader of his Valley of Peace,
      but also needs someone to take his place as Dragon Warrior. As such, he
      will train a new kung fu practitioner for the spot and will encounter a
      villain called the Chameleon who conjures villains from the past.
    trailer: https://www.youtube.com/watch?v=d2OONzqh2jk
    poster: https://image.tmdb.org/t/p/w500/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg
    fanart: https://image.tmdb.org/t/p/w780/kYgQzzjNis5jJalYtIHgrom0gOx.jpg
    deep_link: https://192.168.1.52:443/movie/1011985
  - release: In Theaters $day, $date
    flag: false
    title: Inside Out 2
    runtime: 96
    studio: Pixar
    genres: Animation, Family, Drama
    rating: ""
    summary: >-
      Teenager Riley's mind headquarters is undergoing a sudden demolition to
      make room for something entirely unexpected: new Emotions! Joy, Sadness,
      Anger, Fear and Disgust, who’ve long been running a successful operation
      by all accounts, aren’t sure how to feel when Anxiety shows up. And it
      looks like she’s not alone.
    trailer: https://www.youtube.com/watch?v=LEjhY15eCx0
    poster: https://image.tmdb.org/t/p/w500/gMB8vgHu2lcyzv1fyptD6drHmJd.jpg
    fanart: https://image.tmdb.org/t/p/w780/pI5jxew0I9kub4IXrtsOB8F40dw.jpg
    deep_link: https://192.168.1.52:443/movie/1022789
```

Lastly, can you check to see if you're seeing any errors related to the trakt integration or UMC in your home assistant log?

**Comment by BernieV1977** [comment]
This is the integration I use: https://github.com/dylandoamaral/trakt-integration

--------------------------------------------------------------------------------------------------
```
data: 
- title_default: $title
  line1_default: $episode
  line2_default: $release
  line3_default: $rating - $runtime
  line4_default: $number - $studio
  icon: mdi:arrow-down-bold
- title: Merlina
  poster: https://image.tmdb.org/t/p/w500/oJvYWuL94S4n6KAICe0sexYp3UL.jpg
  fanart: https://image.tmdb.org/t/p/w500/wpkx840m7AXwWsueWaF7yWF5Igk.jpg
  genres: []
  rating: 5.5
  studio: Belgische Radio- en Televisieomroep
  release: $day, $date $time
  airdate: '1987-11-06T23:00:00Z'
  episode: Episode 18
  number: S04E18
- title: Mr. Bean
  poster: https://image.tmdb.org/t/p/w500/pUNQV35kDaKuejnXGNiUeEBurNE.jpg
  fanart: https://image.tmdb.org/t/p/w500/3U11A8yrO0PA9tSdD13UouwEMwE.jpg
  genres:
    - Komedie
    - Familie
  rating: 7.947
  studio: ITV1
  release: $day, $date $time
  airdate: '1994-01-10T00:00:00Z'
  episode: Do-It-Yourself Mr. Bean
  number: S01E09
- title: El día menos pensado
  poster: https://image.tmdb.org/t/p/w500/yVBckwbbL9K5DtiiozsZA1XSwRY.jpg
  fanart: https://image.tmdb.org/t/p/w500/9H07Viv0LZDDtpKpG3fHx8oMeWH.jpg
  genres:
    - Mysterie
    - Sci-Fi & Fantasy
    - Drama
  rating: 5
  studio: Televisión Nacional de Chile
  release: $day, $date $time
  airdate: '2000-07-27T04:00:00Z'
  episode: Episode 8
  number: S02E08
- title: The Island
  poster: https://image.tmdb.org/t/p/w500/t3z8h7rhwiqYH6IiO1NAI6MwJ82.jpg
  fanart: https://image.tmdb.org/t/p/w500/awauKmIBJDVFSNGDcA6GkJMfF5V.jpg
  genres:
    - Komedie
  rating: 9.1
  studio: VRT 1
  release: $day, $date $time
  airdate: '2005-01-22T20:15:00Z'
  episode: Een nieuwe wind
  number: S02E01
- title: The Killing
  poster: https://image.tmdb.org/t/p/w500/vv1yUNoFqww3LoHuZmK4pwjuksY.jpg
  fanart: https://image.tmdb.org/t/p/w500/iLvnc1aK2b2PNQhbyn4IVpDcmcX.jpg
  genres:
    - Misdaad
    - Mysterie
    - Drama
  rating: 7.969
  studio: DR1
  release: $day, $date $time
  airdate: '2007-02-11T19:00:00Z'
  episode: Episode 6
  number: S01E06
- title: Sara
  poster: https://image.tmdb.org/t/p/w500/en0VYyFU9COw8xCuwIMPro2tmdE.jpg
  fanart: https://image.tmdb.org/t/p/w500/fkn704BTYzc7ciN1gMYqc6FljiE.jpg
  genres:
    - Drama
    - Soap
  rating: 6
  studio: VTM
  release: $day, $date $time
  airdate: '2007-09-26T16:30:00Z'
  episode: Episode 2
  number: S01E02
- title: The Zoo (AU)
  genres:
    - Documentaire
  studio: Seven Network
  release: $day, $date $time
  airdate: '2009-06-09T09:00:00Z'
  episode: Episode 5
  number: S03E05
- title: K2 zoekt K3
  genres: []
  release: $day, $date $time
  airdate: '2009-08-21T22:00:00Z'
  episode: Episode 1
  number: S01E01
- title: Breaking Bad
  poster: https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg
  fanart: https://image.tmdb.org/t/p/w500/9faGSFi5jam6pDWGNd0p8JcJgXQ.jpg
  genres:
    - Drama
    - Misdaad
  rating: 8.909
  studio: AMC
  release: $day, $date $time
  airdate: '2010-03-22T01:00:00Z'
  episode: No Más
  number: S03E01
- title: The Killing
  poster: https://image.tmdb.org/t/p/w500/mOzYV3QH5Nwm8CwkVIUmb0Ae0IO.jpg
  fanart: https://image.tmdb.org/t/p/w500/LjXBJaNaBGgAsNHDYfFTwGOUWb.jpg
  genres:
    - Drama
    - Misdaad
    - Mysterie
  rating: 7.867
  studio: AMC
  release: $day, $date $time
  airdate: '2011-05-02T01:00:00Z'
  episode: What You Have Left
  number: S01E06
- title: The Zoo (London UK)
  genres:
    - Documentaire
  studio: ITV1
  release: $day, $date $time
  airdate: '2012-08-05T19:00:00Z'
  episode: Episode 2
  number: S02E02
- title: Loslopend Wild
  poster: https://image.tmdb.org/t/p/w500/5RnTpYDwtbAQkWeIkPC8OiPmZCF.jpg
  fanart: https://image.tmdb.org/t/p/w500/uvtcm8Kn67LH66AP2PqFLZeWk3G.jpg
  genres:
    - Komedie
  rating: 10
  studio: VRT 1
  release: $day, $date $time
  airdate: '2012-12-26T23:00:00Z'
  episode: Aflevering 3
  number: S01E03
- title: The House That £100k Built
  poster: https://image.tmdb.org/t/p/w500/4EwrfzvFC1wsz9HOslvQRVa7jsX.jpg
  genres:
    - Documentaire
    - Reality
  studio: BBC One
  release: $day, $date $time
  airdate: '2013-10-16T19:00:00Z'
  episode: Jane and Andy
  number: S01E05
- title: Silent Witness
  poster: https://image.tmdb.org/t/p/w500/9JHIvbCsGTO4KzozHcMxYxGmAZ1.jpg
  fanart: https://image.tmdb.org/t/p/w500/5WmkDjpgqwO3nU11YEmlSSx8YhH.jpg
  genres:
    - Misdaad
    - Drama
  rating: 7.5
  studio: BBC One
  release: $day, $date $time
  airdate: '2014-01-31T21:00:00Z'
  episode: Fraternity (2)
  number: S17E10
- title: The Sky is the Limit
  poster: https://image.tmdb.org/t/p/w500/6ebCGZZG6lfoOP30SwbQ43iycYL.jpg
  fanart: https://image.tmdb.org/t/p/w500/s5z7kXJ46cyoABU51yKxwqXNGxP.jpg
  genres: []
  rating: 7
  studio: Play4
  release: $day, $date $time
  airdate: '2014-02-04T19:30:00Z'
  episode: Episode 1
  number: S01E01
- title: The Detectives
  fanart: https://image.tmdb.org/t/p/w500/7MJMGIJWm6BtmFJhRorXKBoEBo7.jpg
  genres: []
  studio: Play4
  release: $day, $date $time
  airdate: '2014-11-11T19:30:00Z'
  episode: null
  number: S01E01
- title: The 100
  poster: https://image.tmdb.org/t/p/w500/wcaDIAG1QdXQLRaj4vC1EFdBT2.jpg
  fanart: https://image.tmdb.org/t/p/w500/hTExot1sfn7dHZjGrk0Aiwpntxt.jpg
  genres:
    - Sci-Fi & Fantasy
    - Drama
    - Action & Adventure
  rating: 7.9
  studio: The CW
  release: $day, $date $time
  airdate: '2015-02-26T01:00:00Z'
  episode: Bodyguard of Lies
  number: S02E14
- title: Alloo In de Buitenlandse Gevangenis
  poster: https://image.tmdb.org/t/p/w500/s6sspL9hPcbrPwpxFJVevWYiGvt.jpg
  fanart: https://image.tmdb.org/t/p/w500/gWiSPM1NFDtdB9kkQ1972aDxGgg.jpg
  genres:
    - Misdaad
    - Documentaire
  rating: 6
  studio: VTM
  release: $day, $date $time
  airdate: '2015-03-08T23:00:00Z'
  episode: Episode 1
  number: S01E01
- title: The Zoo (Ireland)
  genres: []
  release: $day, $date $time
  airdate: '2015-04-09T18:30:00Z'
  episode: Episode 1
  number: S06E01
- title: Vera
  poster: https://image.tmdb.org/t/p/w500/7qpXXG6Izo0NvmxHib2SKRDXmXQ.jpg
  fanart: https://image.tmdb.org/t/p/w500/6LQdA5QPX7tjxPxD3l6hufGA2Ko.jpg
  genres:
    - Misdaad
    - Drama
    - Mysterie
  rating: 7.375
  studio: ITV1
  release: $day, $date $time
  airdate: '2015-04-26T19:00:00Z'
  episode: Shadows in the Sky
  number: S05E04
- title: The Bunker
  poster: https://image.tmdb.org/t/p/w500/ddVzqtmnJj0SIzXpavvvlT2T7Zu.jpg
  fanart: https://image.tmdb.org/t/p/w500/v67oNgPmHfg5qJSsiBBD1r5sR4M.jpg
  genres:
    - Action & Adventure
    - Mysterie
  rating: 6.7
  studio: VTM
  release: $day, $date $time
  airdate: '2015-08-30T22:00:00Z'
  episode: Black Bloc
  number: S01E01
- title: Merci Merckx
  genres: []
  release: $day, $date $time
  airdate: '2015-09-01T22:00:00Z'
  episode: null
  number: S01E01
- title: Hinterland
  poster: https://image.tmdb.org/t/p/w500/uyYp5sZqTkviCtRjQNuOuqWTssM.jpg
  fanart: https://image.tmdb.org/t/p/w500/ufYKAjcLR4dDDM5PInW7Cjqvrs8.jpg
  genres:
    - Misdaad
    - Drama
    - Mysterie
  rating: 7.358
  studio: S4C
  release: $day, $date $time
  airdate: '2015-09-27T20:00:00Z'
  episode: 'Episode 2: Part 1'
  number: S02E03
- title: Temptation Island (NL)
  poster: https://image.tmdb.org/t/p/w500/8bwcaIeAoWFMgoOLtZ0MRgNaVXz.jpg
  fanart: https://image.tmdb.org/t/p/w500/elnDOBSZFLNHuwxMZ2P8ekNiyFx.jpg
  genres:
    - Reality
  rating: 4
  studio: RTL 5
  release: $day, $date $time
  airdate: '2016-02-03T23:00:00Z'
  episode: Aflevering 1
  number: S01E01
- title: Bordertown (FI)
  poster: https://image.tmdb.org/t/p/w500/lGses7HbyZeHJu97quAeAjhiXjs.jpg
  fanart: https://image.tmdb.org/t/p/w500/tc7nHHGx8XCZjVvAZ0oUkExhidR.jpg
  genres:
    - Misdaad
    - Mysterie
    - Drama
    - Komedie
  rating: 7.3
  studio: Yle TV1
  release: $day, $date $time
  airdate: '2016-10-30T19:15:00Z'
  episode: The Dolls' House (3)
  number: S01E03
- title: De Kroongetuigen
  poster: https://image.tmdb.org/t/p/w500/jIN4GEpzlEgxBcLCTRsg1zQsVMZ.jpg
  fanart: https://image.tmdb.org/t/p/w500/dlFvZf8laiIwCDLt6jm50wpQGwW.jpg
  genres:
    - Documentaire
    - Misdaad
  studio: VTM
  release: $day, $date $time
  airdate: '2017-03-02T20:35:00Z'
  episode: The vampire of Muizen
  number: S04E08
- title: Tegen De Sterren Op
  poster: https://image.tmdb.org/t/p/w500/6pQo5SbRnF4G1OYHZ14k7oimYn4.jpg
  fanart: https://image.tmdb.org/t/p/w500/d4VSu4PNcnb2GYOcXLABFGNxkwS.jpg
  genres:
    - Komedie
    - Reality
  rating: 7.5
  studio: VTM
  release: $day, $date $time
  airdate: '2017-03-08T19:35:00Z'
  episode: Episode 3
  number: S07E03
- title: Moerkerke en de vrouwen
  genres:
    - Documentaire
    - Reality
  studio: VTM
  release: $day, $date $time
  airdate: '2017-04-18T19:50:00Z'
  episode: null
  number: S01E06
- title: Bargoens
  fanart: https://image.tmdb.org/t/p/w500/rcEL4Vjddu6wmHkbOYGBewDhOf4.jpg
  genres: []
  studio: VRT 1
  release: $day, $date $time
  airdate: '2017-08-29T18:35:00Z'
  episode: Episode 1
  number: S01E01
- title: Alloo in the Night
  poster: https://image.tmdb.org/t/p/w500/gpXSUddKvHpmuBFnY360PxRyeZ.jpg
  genres: []
  rating: 6
  release: $day, $date $time
  airdate: '2017-09-07T19:45:00Z'
  episode: null
  number: S01E01

unit_of_measurement: shows
icon: mdi:calendar
friendly_name: Trakt Next To Watch Only Aired`
```
--------------------------------------------------------------------------------------------------

Sometimes there are some fetching erros in the HA logs: 

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.trakt_tv
Bron: helpers/update_coordinator.py:315
integratie: Trakt (documentatie, problemen)
Eerst voorgekomen: 21 mei 2024 om 20:10:20 (1 gebeurtenissen)
Laatst gelogd: 21 mei 2024 om 20:10:20

Unexpected error fetching trakt data
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.12.1/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.pyenv/versions/3.12.1/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/dietpi_userdata/homeassistant/custom_components/trakt_tv/apis/trakt.py", line 446, in retrieve_data
    sources_data = await gather(*coroutine_sources_data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/dietpi_userdata/homeassistant/custom_components/trakt_tv/apis/trakt.py", line 342, in fetch_upcomings
    data = await gather(
           ^^^^^^^^^^^^^
  File "/mnt/dietpi_userdata/homeassistant/custom_components/trakt_tv/apis/trakt.py", line 280, in fetch_upcoming
    raw_medias = [media for medias in data for media in medias]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable


Hope this helps.

**Comment by mkanet** [comment]
Hi @BernieV1977 I want you to know that I didnt forget about you.  I tried to install [the trakt integration](https://github.com/dylandoamaral/trakt-integration) to make a fix for it right after you mentioned the integration you used.  However, it doesnt seem to be compatible with Home Assistant behind a NGINX reverse proxy.  At least, it wont work on my Home Assistant setup.  I [submitted a bug](https://github.com/dylandoamaral/trakt-integration/issues/102) on the trakt repo.  I haven't heard back yet from the developer for that integration.

In the meantime, do you have Plex, Radarr, Sonarr, or Steam (gaming) installed?  If so, maybe you could test the other integrations with UMC's sort_by feature; which should work just fine.  If not, then there is most likely something wrong with your UMC installation.

**Comment by BernieV1977** [comment]
Hi,
I'm using the trakt integration behind an nginx reverse proxy.
I'm running HA Core version.

**Comment by mkanet** [comment]
> Hi, I'm using the trakt integration behind an nginx reverse proxy. I'm running HA Core version.

I'm using Home Assistant OS.  **Maybe you wouldn't mind sharing your NGINX config?**  The Trakt integration is the first and only integration I've not been able to get working on Home Assistant in the last several years.  If I can get the Trakt integration working, I will be able to hopefully reproduce your issue.

Also, maybe you wouldn't mind testing one of the other integrations I mentioned with UMC to confirm the issue on your setup is specific to Trakt only or not.

**Comment by mkanet** [comment]
Hi @BernieV1977 are you still interested in getting help for this?  If so, please reply to my last message.  Otherwise, Ill presume you already got the sort_by feature to work for you.

**Comment by BernieV1977** [comment]
Hi, yes I'm still interested but l'm some days from home. I send you my nginx config this weekend. I cannot test other integrations Because I don't have other media system. Tia

**Comment by mkanet** [comment]
Thanks for replying.  Actually , I just noticed in the title of this issue, it says you can't get the `sort_by` feature to work with the **plex recently added** integration.  I know that:  https://github.com/custom-components/sensor.plex_recently_added definitely works with UMC's `sort_by` feature.  However, I wouldn't mind getting the trakt integration to work anyway on my setup.  So, please provide your full NGINX config for your Home Assistant instance.

When you get a chance, can you please try the following; especially the step completely deleting your browser's cache.

1) Re-download both UMC and Plex Recently Added integrations.  Make sure the files actually get replaced (if possible)
1) Delete your web browser's cache. 
2) Restart Home Assistant
3) Copy and paste the below yaml code "as is", the only thing you might need to change is the sensor name to your plex movies sensor: I.E., `sensor.plex_recently_added_movie` 

```
title: Movies
type: custom:upcoming-media-card
entity: sensor.plex_recently_added_movie
image_style: fanart
hide_empty: true
box_shadows: true
enable_tooltips: true
enable_transparency: true
sort_by: airdate
collapse: flag=true
```

We need to see what part of your setup is different than users that are currently using the `sort_by` feature.

**Comment by BernieV1977** [comment]
As I said before I cannot test the Plex or other integration because I don't have a mediaserver system. The problem with sorting I have is with the Trakt integration (I know this is the topic about Plex integration sorting problems so maybe you split this).

This is my config in HA configuration.yaml:


```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - X.X.X.X     # Add the IP address of the nginx proxy server

```

If you should have 
 base_url: 
 ssl_certificate: 
 ssl_key: 

in the section http of your configuration.yaml then remove it.

-------- nginx config -----------------

```
server {
    listen 80;
    listen [::]:80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    server_name  your.domain.org;


    listen 443 ssl;
    ssl_certificate /pathtoyourfullchainfile/fullchain.pem;
    ssl_certificate_key /pathtoyourprivkeyfile/privkey.pem;

    location / {

        proxy_pass http://yourlocalipha:8123;
        proxy_set_header Host $host;
        proxy_redirect http:// https://;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        proxy_connect_timeout       600;
        proxy_send_timeout          600;
        proxy_read_timeout          600;
        send_timeout                600;

```

**Comment by mkanet** [comment]
Thank you.  I guess the issue isn't related to my NGINX config since mine is more or less  the same config. The trakt integration developer just replied to me.  I'll try a few more things to see if I can get it working.

**Comment by mkanet** [comment]
I appreciate how patient and polite your posts are here, I promise to be just as patient with you.  Please forgive me in case I ask you something that you might have already tried.  We need to confidently rule out each possibility.

Anyway, I have good news.  I was able to add the trakt integration.  It was super easy.  The only thing I wasn't doing wrong was adding the wrong redirect URL on the trakt website.

**I was able to confirm the 'sort_by' feature of UMC can sort by _(title, rating, airdate, etc_) (with any the trakt sensor) on my Home Assistant instance.**

For example, the below card code works as expected:

```yaml
type: custom:upcoming-media-card
entity: sensor.trakt_recommendation_movies
title: Movie Recommendations
image_style: fanart
hide_empty: true
sort_by: airdate
title_text: $title
line1_text: $release
line2_text: 'Rating: $rating'
line3_text: $runtime
line4_text: $studio
max: 10
```

At least, we can narrow down the cause a little more... we now know we need to focus on your configuration specifically, not the UMC or any other supported integration for UMC.

**Please confirm:**

1. **Are you certain that when you specify what attribute to sort by, you are NOT preceding the attribute with a $ character?**
Make sure it is:  `sort_by: title`  and NOT `sort_by: $title`.  Also make sure there is only one space character in:  `sort_by: $title`

2.  **Can you please confirm that in Home Assistant HACS/Frontend displays: the following at the top/left section of your screen:**
![image](https://github.com/custom-cards/upcoming-media-card/assets/811008/a3d4b2d3-b6d5-4078-ac98-32eb2ca65f71)

3. **Lastly, I don't know if this if possible for you to do or not, can you also navigate to the respective folder where UMC card code is installed** I.E., `/config/www/community/upcoming-media-card/upcoming-media-card.js`, open this file in notepad or any text editor to see if you can find `// START: 'sort_by' and 'sort_ascending' features` somewhere in the code? 

4. Remove UMC completely from your Home Assistant instance.  Confirm that that the folder `/config/www/community/upcoming-media-card` and its contents is completely removed.  Then, reboot Home Assistant.  Finally, reinstall UMC Version 0.5.5 again.

Let me know when you get a chance.
