### ISSUE TITLE
disable_hyperlinks doesn't function

### ISSUE THREAD

**Issue by lichenophile** [custom-cards/upcoming-media-card#96]
## Describe the bug:
adding `disable_hyperlinks: true` does not prevent clicking items that lead to *arr pages

## Config YAML:
```YAML
                - type: custom:upcoming-media-card
                  title: ↔ Upcoming Films
                  date: ddmm
                  clock: 24
                  max: 66
                  entity: sensor.radarr_upcoming_media
                  image_style: fanart
                  title_text: $title
                  line1_text: $genres
                  line2_text: $runtime - $rating
                  line3_text: $release, $time
                  line4_text: $studio
                  title_size: medium
                  line_size: small
                  border_color: "#f92aad66"
                  hide_empty: false
                  sort_by: airdate
                  sort_ascending: true
                  enable_tooltips: true
                  enable_transparency: true
                  enable_trailers: true
                  flag: false
                  box_shadows: false
                  disable_hyperlinks: true
```

## Components:
This issue seems present when powering the card with either *arr upcoming media custom components

## HA Error:
No HA error logs present that I could find

## Troubleshooting Guide:
I have given it a read, nothing related to this issue present.

## Home Assistant Version:
Core 2024.6.4
Supervisor 2024.06.0
Operating System 12.4
Frontend 20240610.1

## Screenshots:
Not helpful in this case

## Additional Context:
I discovered this issue when attempting to set `enable_trailers: true` for the media which I have checfked is supplying a trailer within the radarr sensor data. 
This did not open the trailer upon clicking, instead leading to the movies listing in my radarr instance. 
So I tried `disable_hyperlinks` in case the deep link was overriding, which caused me to discover that `disable_hyperlinks` doesn't seem to work regardless if the item has a trailer or not, or is an item form the sonarr or radarr sensor. 

This issue may be the cause of `enable_trailers` not functioning correctly, so I will hold off on making an issue for that until this is solved, just in case.

Ideally, I would like to be able to disable deep links being clicked through by users but still allow trailers to be played.
